### ISSUE TITLE
CSNF - Concept Intro Link is Broken

### ISSUE THREAD

**Issue by DennisFaucher** [onug/CSNF#22]
https://github.com/onug/CSNF/blob/main/demos/demos/csnf#cloud-security-notifications-framework leads to 404

**Comment by DennisFaucher** [comment]
Actually, all three of the demo links are broken

**Comment by michaelthomasclark** [comment]
Thanks @DennisFaucher - Apologies for the belated response - stay tuned for resolution (this week I hope!)

**Comment by rjulian** [comment]
Fixed in #23 Thanks a ton @DennisFaucher
